import { StyleSheet } from 'react-native';


export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 10,
    backgroundColor: '#F8FAFC',
    position: 'relative',
    paddingLeft: 10,
    height: '80%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  box: {
    flex: 1,
    // flexDirection: 'column',
    // justifyContent: 'space-between',
    // alignItems: 'center',
    backgroundColor: '#FFFFFF',
    // verticalAlign: 'middle',
    width: '100%',
    height: 100,
    marginVertical: 10,
    // paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#211071',
  },
  boxContent: {
    flex: 1,
    flexDirection: 'row',
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  leaderboardTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
    width: '25%',
    alignSelf: 'center',
    textAlign: 'center',
  },
  matchContainer: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    backgroundColor: '#F8FAFC',
    position: 'relative',
    paddingLeft: 10,
    height: '80%',
  },
  matchScroll: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
    backgroundColor: '#F8FAFC',
    position: 'relative',
    height: '80%',
  },
  matchBox: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    verticalAlign: 'middle',
    width: '100%',
    height: 100,
    marginVertical: 10,
    // paddingHorizontal: 10,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#211071',
  },
  matchLinkBox: {
    flex: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#F8FAFC',
    verticalAlign: 'middle',
    width: '100%',
    height: 120,
    // marginTop: 60,
    // marginBottom: 60,
    marginVertical: 60,
    // paddingVertical: 60,
  },
  matchNextBox: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    verticalAlign: 'middle',
    width: '100%',
    height: 120,
    marginTop: 60,
    marginBottom: 60,
    borderTopLeftRadius: 8,
    borderBottomLeftRadius: 8,
    borderRightWidth: 0,
    borderWidth: 1,
    borderColor: '#211071',
  },
  matchBoxContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
  },
  matchInputContent: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
  },
  matchupView: {
    flex: 1,
    flexDirection: 'row',
    margin: 10,
  },
  matchLinkBoxContent1: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    borderRadius: 8,
    borderWidth: 1,
    borderLeftWidth: 0,
    borderBottomLeftRadius: 0,
    borderTopLeftRadius: 0,
    borderColor: '#211071',
  },
  matchLinkBoxContent2: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: '100%',
    borderColor: '#211071',
  },
  matchBr: {
    borderBottomWidth: 1,
    borderColor: '#211071',
    alignSelf: 'stretch',
    height: 1,
    width: '100%',
  },
  matchTitle: {
    paddingHorizontal: 10,
    fontSize: 18,
    fontWeight: 'bold',
  },
  matchTitleLeft: {
    paddingHorizontal: 10,
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  nextPageText: {
    paddingHorizontal: 10,
    fontSize: 26,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  matchButtonTitle: {
    paddingHorizontal: 10,
    fontSize: 18,
    fontWeight: 'bold',
    alignItems: 'center',
    verticalAlign: 'middle',
    marginBottom: 5,
  },
  matchButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 8,
    elevation: 3,
    backgroundColor: 'white',
    height: 50,
  },
  leaderboardContainer: {
    flex: 1,
    padding: 10,
    backgroundColor: '#F8FAFC',
    position: 'relative',
    paddingLeft: 10,
    height: '80%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'flex-start',
  },
  leaderboardBox: {
    flex: 1,
    flexDirection: 'column',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
    verticalAlign: 'middle',
    width: '100%',
    height: 50,
    // borderRadius: 8,
    borderWidth: 1,
    borderTopWidth: 0,
    borderColor: '#211071',
  },
  byeTitle: {
    paddingHorizontal: 10,
    fontSize: 18,
    fontWeight: 'bold',
    alignItems: 'center',
    marginBottom: 5,
  },
  matchPosition: {
    fontSize: 18,
    fontWeight: 'bold',
    textAlign: 'left',
    marginBottom: 5,
  },
  matchCups: {
    fontSize: 16,
  },
  inputContainer: {
    flexDirection: 'column',
    alignItems: 'flex-start',
  },
  input: {
    flex: 1,
    marginLeft: 15,
    marginRight: 15,
    paddingLeft: 9,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    height: 40,
  },
  inputHeader: {
    alignItems: "center",
    paddingLeft: 25,
    paddingBottom: 5,
    fontWeight: 'bold',
    color: '#211071',
  },
  deleteButton: {
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 10,
    padding: 10,
  },
  teamContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  matchSingleButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    borderRadius: 8,
    elevation: 3,
    backgroundColor: '#211071',
    height: 50,
  },
  singleButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    marginLeft: 15,
    marginRight: 15,
    borderRadius: 8,
    elevation: 3,
    backgroundColor: '#211071',
    height: 50,
  },
  primaryButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    marginLeft: 7.5,
    marginRight: 15,
    borderRadius: 8,
    elevation: 3,
    backgroundColor: '#211071',
    height: 50,
  },
  primaryText: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: 'white',
  },
  secondaryButton: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    marginLeft: 15,
    marginRight: 7.5,
    borderRadius: 8,
    elevation: 3,
    backgroundColor: 'white',
    height: 50,
  },
  secondaryText: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: '#211071',
  },
  buttonStyleContainer: {
    flex: 1,
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    flexDirection: 'column',
    // paddingHorizontal: 20,
    paddingBottom: 15,
    paddingTop: 15,
    backgroundColor: '#F8FAFC',
  },
  buttonInnerContainer: {
    flex: 1,
    textAlignVertical: 'center',
    flexDirection: 'row',
    // paddingHorizontal: 20,
    paddingBottom: 5,
    paddingTop: 5,
    backgroundColor: '#F8FAFC',
  },
  buttonInnerContainerPageNumber: {
    flex: 1,
    textAlignVertical: 'center',
    flexDirection: 'row',
    backgroundColor: '#F8FAFC',
  },
  centerHorizontally: {
    flex: 1,
    alignItems: 'center',
  },
  matchButtonStyleContainer: {
    // flex: 1,
    // bottom: 0,
    // left: 0,
    // right: 0,
    // flexDirection: 'row',
    // paddingHorizontal: 20,
    // paddingBottom: 15,
    // paddingTop: 15,
    backgroundColor: '#F8FAFC',
  },
  gamesContainer: {
    height: '100%'
  },
  inputView: {
    height: 40,
    width: '100%',
  },
  matchupButtonView: {
    height: 40,
    width: '49%',
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
  },
  addTeamsView: {
    left: 0,
    right: 0,
    height: 55,
    width: '100%',
    paddingBottom: 8,
    paddingTop: 8,
  },
  gamesView: {
    left: 0,
    right: 0,
    height: 80,
    width: '100%',
    paddingBottom: 8,
    paddingTop: 8,
  },
  gamesButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 15,
    marginRight: 15,
    borderRadius: 8,
    backgroundColor: '#FFFFFF',
    height: 50,
  },
  gamesButtonText: {
    textAlignVertical: 'center',
    fontSize: 16,
    lineHeight: 21,
    marginLeft: 15,
    marginRight: 15,
    fontWeight: 'bold',
    letterSpacing: 0.25,
    color: '#211071',
  },
  addGamesView: {
    left: 0,
    right: 0,
    height: 80,
    width: '100%',
    paddingBottom: 15,
  },
  addGamesButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 15,
    marginRight: 15,
    borderRadius: 8,
    height: 50,
  },
  gamesIcon: {
    marginLeft: 15,
  },
});
